# Generated by Django 3.0.7 on 2020-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruckinfo',
            name='locationId',
            field=models.IntegerField(default=0),
        ),
    ]
