# Generated by Django 3.0.7 on 2020-06-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatorApp', '0002_foodtruckinfo_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckinfo',
            name='foodItems',
            field=models.CharField(max_length=300),
        ),
    ]
