# Generated by Django 3.0.7 on 2020-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatorApp', '0003_auto_20200604_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckinfo',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
